- shell:
    - [defaults -currentHost write -g AppleFontSmoothing -int 0]
    - [defaults write -g CGFontRenderingFontSmoothingDisabled -bool true]
    - [sudo scutil --set ComputerName "⚡️ luizkowalski"]
    - [sudo scutil --set HostName "luizkowalski"]
    - [sudo scutil --set LocalHostName "luizkowalski"]
    - [sudo nvram SystemAudioVolume=" "]
    - [defaults write com.apple.finder ShowStatusBar -bool true]
    - [defaults write com.apple.finder ShowPathbar -bool true]
    - [defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true]
    - [defaults write com.apple.dock autohide -bool true]
    - [defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 80]
    - [defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false]
    - [defaults write NSGlobalDomain AppleLanguages -array "en" "pt-BR"]
    - [defaults write NSGlobalDomain AppleLocale -string "en_DE@currency=EUR"]
    - [defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"]
    - [defaults write NSGlobalDomain AppleMetricUnits -bool true]
