- defaults:
    link:
      create: true
      relink: true
      force: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ~/.gitconfig: files/.gitconfig
    ~/.gitignore: files/.gitignore
    ~/.aliases: files/.aliases
    ~/.functions: files/.functions
    ~/.zshrc: files/.zshrc
    ~/.config/topgrade.toml: files/topgrade.toml
    ~/.gemrc: files/.gemrc

- shell:
    - [sh -c "scripts/install_p10k", "Installing p10k"]
    - [cp files/.p10k.zsh ~/.p10k.zsh, "Copying p10k config"] # For some reason, linking this file doesn't work, it has to be copied
    - [sh -c "scripts/install_zsh_autosuggestions", "Installing zsh-autosuggestions"]
