- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true
- link:
    ~/.gitconfig: files/.gitconfig
    ~/.gitignore: files/.gitignore
    ~/.aliases: files/.aliases
    ~/.functions: files/.functions
    ~/.zshrc: files/.zshrc
    ~/.gemrc: files/.gemrc
    ~/.config/topgrade.toml: files/topgrade.toml
    ~/.config/starship.toml: files/starship.toml
    ~/.config/zed/keymap.json: files/zed/keymap.json
    ~/.config/zed/settings.json: files/zed/settings.json

- shell:
    - [sh -c "scripts/install_zsh_autosuggestions", "Installing zsh-autosuggestions"]
    - [sh -c "scripts/install_zsh_syntax_highlight", "Installing zsh-syntax-highlight"]
