[gcloud]
disabled = true

[directory]
read_only = "󰌾 "

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style) coding in '

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[golang]
symbol = " "

[python]
disabled = true

# [java]
# symbol = " "

[memory_usage]
symbol = " "
threshold = 75
disabled = true

[nodejs]
symbol = " "
disabled = true

# [package]
# symbol = " "

[rust]
symbol = " "

[ruby]
symbol = "💎 "

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '
# disabled = true

[[battery.display]]
threshold = 80

# [shell]
# unknown_indicator = 'mystery shell'
# style = 'red bold'
# disabled = false
