[gcloud]
disabled = true

[directory]
read_only = " 󰌾"

[hostname]
ssh_only = false

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[golang]
symbol = " "

[python]
disabled = false

# [java]
# symbol = " "

[memory_usage]
symbol = "💾 "
threshold = 5
disabled = false

[nodejs]
symbol = " "

# [package]
# symbol = " "

[rust]
symbol = " "

[ruby]
symbol = "💎 "

[battery]
disabled = true

# [shell]
# unknown_indicator = 'mystery shell'
# style = 'red bold'
# disabled = false
